# Generated by Django 5.1.2 on 2024-11-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_admin', models.CharField(max_length=100)),
                ('telepon_admin', models.CharField(max_length=15)),
                ('id_akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=100)),
                ('telepon_customer', models.CharField(max_length=15)),
                ('alamat_customer', models.TextField()),
                ('id_akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.akun')),
            ],
        ),
    ]
